Move svn-url into SVN_URL env var in dotfile

diff --git a/svn-push b/svn-push
--- a/svn-push
+++ b/svn-push
@@ -9,8 +9,18 @@ cd "$( dirname $0 )"
 dev_lib_dir=$(pwd)
 cd ..
 
+
+if [ -e .dev-lib ]; then
+	source .dev-lib
+elif [ -e .ci-env.sh ]; then
+	source .ci-env.sh
+fi
 if [ ! -e svn-url ]; then
-	echo "Error: Missing svn-url file" >&2
+	SVN_URL=$(cat svn-url)
+fi
+
+if [ -z "$SVN_URL" ]; then
+	echo "Error: Missing SVN_URL" >&2
 	exit 1
 fi
 
@@ -48,7 +58,7 @@ fi
 
 git pull --ff-only origin master
 git push origin master
-svn_url=$(cat svn-url)
+SVN_URL=$(cat svn-url)
 git_root_hash=$(md5sum <<< "$git_root" | cut -c1-32)
 plugin_uniq_slug="$(basename "$git_root")-$git_root_hash"
 lock_file="/tmp/$plugin_uniq_slug.lock"
@@ -96,7 +106,7 @@ touch "$lock_file"
 
 # SVN: Checkout or update
 if [ ! -e $svn_tmp_repo_dir ]; then
-	svn checkout $svn_url $svn_tmp_repo_dir
+	svn checkout $SVN_URL $svn_tmp_repo_dir
 	cd $svn_tmp_repo_dir
 else
 	cd $svn_tmp_repo_dir
@@ -115,6 +125,7 @@ fi
 # rsync all committed files from the Git repo to SVN
 rsync -avz --delete --delete-excluded \
 	--exclude '/.ci-env.sh' \
+	--exclude '/.dev-lib' \
 	--exclude '/.coveralls.yml' \
 	--exclude '/.git*' \
 	--exclude '/.jscsrc' \
